[WFMP-154] Integrate Channels to provision WildFly
wildfly/wildfly-maven-plugin pull request #228
Opened 2022-05-04 15:26 UTC by jmesnil

JIRA: https://issues.redhat.com/browse/WFMP-154

2022-05-05 06:32 UTC, jmesnil commented
the JDK8 Jobs fails as the integrated `wildfly-channel` targets Java 11: https://github.com/wildfly-extras/wildfly-channel/blob/2e798760d37da1290eaa8a7d22526cdf1db5fb1a/pom.xml#L26

2022-05-05 06:33 UTC, jmesnil commented on core/src/main/java/org/wildfly/plugin/core/GalleonUtils.java
> +                //Special case for G:A that conflicts with producer:channel that we can't have in the plugin.
@jfdenise this is a change for your PoC and I'm not sure if it's still valid. Could you please check?

2022-05-05 06:34 UTC, jmesnil commented on examples/channel/pom.xml
> +                <version>3.0.1-SNAPSHOT</version>
the examples POMs are independent of the maven-plugin-parent POM.
Updating the plugin version will make the examples out of sync. 
This needs to be resolved

2022-05-05 10:02 UTC, jfdenise commented on core/src/main/java/org/wildfly/plugin/core/GalleonUtils.java
> +                //Special case for G:A that conflicts with producer:channel that we can't have in the plugin.
Yes, that is needed to not require to end the G:A with a ":".

2022-05-13 09:15 UTC, jfdenise commented
@jmesnil @jamezp , it would be nice to bump WildFly maven plugin to let's say a 4.0.0.Alpha1 built with JDK11 containing this feature.

2022-05-16 10:06 UTC, jfdenise requested changes

2022-05-16 11:03 UTC, jmesnil commented on examples/channel-example/Dockerfile
> +COPY --chown=jboss:root target/server $JBOSS_HOME
fixed

2022-05-16 11:03 UTC, jmesnil commented on examples/jaxrs/Dockerfile
> +COPY --chown=jboss:root target/server $JBOSS_HOME
fixed

2022-05-16 11:10 UTC, jmesnil commented on plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java
> +public class ChannelMavenArtifactRepositoryManager implements MavenRepoManager {
Good suggestion, tracked by https://github.com/wildfly-extras/wildfly-channel/issues/36

2022-05-16 12:55 UTC, jmesnil commented on plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java
> +public class ChannelMavenArtifactRepositoryManager implements MavenRepoManager {
> order for Galleon-plugins installer to detect that the channel are in place

I don't get that part. "Channels are in place" when their are in the plugin `<configuration>`. That's when we decide if we want to resolve artifacts using channels or doing it directly from the feature-pack's metadata. What would this marker interface change with that regard?

2022-05-16 13:03 UTC, jfdenise commented on plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java
> +public class ChannelMavenArtifactRepositoryManager implements MavenRepoManager {
The Galleon plugins: https://github.com/wildfly/galleon-plugins/tree/main/galleon-plugins, during installation, can take decision according to the fact that the feature-pack is provisioned with channels or without. An example is the expression resolution used for versions (datasources feature-pack). The expression must be resolved to a version when channels are not configued. When channels are configured, the expression is to be ignored (no need for system property or env variable to be set to define the version to provision), the channel rules all versions. Obviously if no stream is defined in a configured channel, the expression must be properly resolved.

2022-05-17 13:52 UTC, jmesnil commented
@jfdenise I've released https://github.com/wildfly-extras/wildfly-channel/releases/tag/1.0.0.Alpha13 that incorporates your changes. I've updated this PR with this release (including the `org.wildfly.channel.spi.ChannelResolvable` marker interface). Could you please give it a second look?

2022-05-23 15:20 UTC, jamezp commented
Overall this looks fine to me. The only thing I'm not sure about is having the example in the same project. I've always preferred to have examples separate from the project source. I don't have a real strong opinion on it though.

2022-05-24 08:47 UTC, jmesnil commented
@jamezp the main argument against having them in their repo is that the examples are not tied to the parent POM and they can get out of sync if we do not update the plugin version in their pom.xml. Having them outside of the project might make more sense but where could we host them? Do you mean creating  new repo `wildfly/wildfly-maven-plugin-examples?

2022-05-24 18:17 UTC, jamezp commented
> @jamezp the main argument against having them in their repo is that the examples are not tied to the parent POM and they can get out of sync if we do not update the plugin version in their pom.xml. Having them outside of the project might make more sense but where could we host them? Do you mean creating new repo `wildfly/wildfly-maven-plugin-examples`?

Hi @jmesnil. One thing I personally do no like is having standalone projects/modules depend on a SNAPSHOT artifact. It just feels not very user friendly. However, I realize that's a perfect world scenario which we do not always live in :)

As for where it could live outside of the project. I would be fine with a new repository or using the quickstarts if we feel that is the appropriate place.

2022-05-30 09:33 UTC, jmesnil commented
@jamezp As discussed, I've removed the examples from the plugin source code. The quickstarts will eventually be updated to use the plugin to deploy WildFly so that's where the users will actually see the usage of the plugin.

2022-05-31 14:47 UTC, jamezp approved these changes

2022-05-31 14:48 UTC, merged