Fix for WFMP-257 and WFMP-258
wildfly/wildfly-maven-plugin pull request #534
Opened 2024-05-23 12:45 UTC by jfdenise

Issues:
* https://issues.redhat.com/browse/WFMP-257
* https://issues.redhat.com/browse/WFMP-258

2024-05-31 00:25 UTC, jamezp requested changes
Could I get a little more information on why this change is needed? The JIRA's don't really say much :)

2024-05-31 00:25 UTC, jamezp commented on plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
None of the changes in this file should be needed.

2024-05-31 00:25 UTC, jamezp commented on plugin/src/main/java/org/wildfly/plugin/common/GlowMavenMessageWriter.java
> +    public GlowMavenMessageWriter(Log log) {
This change does not appear to be needed.

2024-05-31 00:25 UTC, jamezp commented on plugin/src/main/java/org/wildfly/plugin/provision/AbstractPackageServerMojo.java
> +    protected OfflineCommandExecutor commandExecutor;
This can be private.

2024-08-26 13:31 UTC, closed without merging

2024-08-26 13:31 UTC, jfdenise commented
Closing this PR, will open a PR for WFMP-257 only, WFMP-258 will be not done.